Please do not run this notebook, this barely ran even with 64gb of ram

Especially the SVC grid search, that took 5 and a half hours

## Load data

In [1]:
#load the pickled count matrix and tfidf matrix
import pandas as pd
clean_news_data = pd.read_pickle('data/labelled_dtm.pkl')

clean_news_data_ctx = pd.read_pickle('data/labelled_tfidf_dtm.pkl')

In [2]:
clean_news_data.head()

,aaa,aafter,aaliyah,aaplo,aaplus,aaron,aaroncovfefe,aaronshhh,aarp,ab,...,zuker,zukunft,zuppello,zyklon,zypries,zz,zztaine,zzzzaaaacccchhh,zzzzzzzzzzzzz,real_label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [3]:
clean_news_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5182 entries, 0 to 5181
Columns: 53541 entries, aaa to real_label
dtypes: int64(53541)
memory usage: 2.1 GB

In [4]:
clean_news_data['real_label'].value_counts()

real_label
1    2591
0    2591
Name: count, dtype: int64

In [5]:
clean_news_data_ctx.head()

,aaa,aafter,aaliyah,aaplo,aaplus,aaron,aaroncovfefe,aaronshhh,aarp,ab,...,zuker,zukunft,zuppello,zyklon,zypries,zz,zztaine,zzzzaaaacccchhh,zzzzzzzzzzzzz,real_label
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [6]:
clean_news_data_ctx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5182 entries, 0 to 5181
Columns: 53541 entries, aaa to real_label
dtypes: float64(53540), int64(1)
memory usage: 2.1 GB

In [7]:
clean_news_data_ctx['real_label'].value_counts()

real_label
1    2591
0    2591
Name: count, dtype: int64

## Naive Bayes

In [2]:
#train naive bayes models
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score

#initial nb models
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

#split data into train and test
X_train, X_test, y_train, y_test = train_test_split(clean_news_data.drop('real_label', axis=1), clean_news_data['real_label'], test_size = 0.3, random_state = 101)

#fit models
gnb.fit(X_train, y_train)
mnb.fit(X_train, y_train)
bnb.fit(X_train, y_train)

#model predictions
y_pred_gnb = gnb.predict(X_test)
y_pred_mnb = mnb.predict(X_test)
y_pred_bnb = bnb.predict(X_test)

#show model results
print('GaussianNB Accuracy: ', accuracy_score(y_test, y_pred_gnb))
print('MultinomialNB Accuracy: ', accuracy_score(y_test, y_pred_mnb))
print('BernoulliNB Accuracy: ', accuracy_score(y_test, y_pred_bnb))

GaussianNB Accuracy:  0.8861736334405145
MultinomialNB Accuracy:  0.9434083601286174
BernoulliNB Accuracy:  0.9607717041800643

In [3]:
#gaussian nb grid search
from sklearn.model_selection import GridSearchCV

In [ ]:
#gaussian nb grid search
gnb_params = {'var_smoothing': [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12, 1e-13]}

gnb_grid = GridSearchCV(gnb, gnb_params, cv=5, n_jobs=-1, verbose=1)

gnb_grid.fit(X_train, y_train)

print('GaussianNB Best Score: ', gnb_grid.best_score_)
print('GaussianNB Best Params: ', gnb_grid.best_params_)

In [10]:
#multinomial nb grid search
mnb_params = {'alpha': [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12, 1e-13]}

mnb_grid = GridSearchCV(mnb, mnb_params, cv=5, n_jobs=-1, verbose=1)

mnb_grid.fit(X_train, y_train)

print('MultinomialNB Best Score: ', mnb_grid.best_score_)
print('MultinomialNB Best Params: ', mnb_grid.best_params_)

Fitting 5 folds for each of 14 candidates, totalling 70 fits
MultinomialNB Best Score:  0.9434824736392133
MultinomialNB Best Params:  {'alpha': 1}

In [11]:
#bernoulli nb grid search
bnb_params = {'alpha': [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12, 1e-13]}

bnb_grid = GridSearchCV(bnb, bnb_params, cv=5, n_jobs=-1, verbose=1)

bnb_grid.fit(X_train, y_train)

print('BernoulliNB Best Score: ', bnb_grid.best_score_)
print('BernoulliNB Best Params: ', bnb_grid.best_params_)

Fitting 5 folds for each of 14 candidates, totalling 70 fits
BernoulliNB Best Score:  0.9608522846015009
BernoulliNB Best Params:  {'alpha': 1}

In [12]:
#split data into train and test
X_train, X_test, y_train, y_test = train_test_split(clean_news_data_ctx.drop('real_label', axis=1), clean_news_data['real_label'], test_size = 0.3, random_state = 101)

#fit models
gnb.fit(X_train, y_train)
mnb.fit(X_train, y_train)
bnb.fit(X_train, y_train)

#model predictions
y_pred_gnb = gnb.predict(X_test)
y_pred_mnb = mnb.predict(X_test)
y_pred_bnb = bnb.predict(X_test)

#show model results
print('GaussianNB Accuracy: ', accuracy_score(y_test, y_pred_gnb))
print('MultinomialNB Accuracy: ', accuracy_score(y_test, y_pred_mnb))
print('BernoulliNB Accuracy: ', accuracy_score(y_test, y_pred_bnb))

GaussianNB Accuracy:  0.8636655948553055
MultinomialNB Accuracy:  0.9337620578778135
BernoulliNB Accuracy:  0.9607717041800643

In [13]:
#gaussian nb grid search
from sklearn.model_selection import GridSearchCV

gnb_params = {'var_smoothing': [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12, 1e-13]}

gnb_grid = GridSearchCV(gnb, gnb_params, cv=5, n_jobs=-1, verbose=1)

gnb_grid.fit(X_train, y_train)

print('GaussianNB Best Score: ', gnb_grid.best_score_)
print('GaussianNB Best Params: ', gnb_grid.best_params_)

Fitting 5 folds for each of 14 candidates, totalling 70 fits

c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
12 fits failed out of a total of 70.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\naive_bayes.py", line 263, in fit
    return self._partial_fit(
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\naive_bayes.py", line 431, in _partial_fit
    self.epsilon_ = self.var_smoothing * np.var(X, axis=0).max()
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\numpy\_core\fromnumeric.py", line 4008, in var
    return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\numpy\_core\_methods.py", line 185, in _var
    x = asanyarray(arr - arrmean)
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 1.16 GiB for an array with shape (2902, 53540) and data type float64

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\naive_bayes.py", line 263, in fit
    return self._partial_fit(
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\naive_bayes.py", line 431, in _partial_fit
    self.epsilon_ = self.var_smoothing * np.var(X, axis=0).max()
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\numpy\_core\fromnumeric.py", line 4008, in var
    return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\numpy\_core\_methods.py", line 185, in _var
    x = asanyarray(arr - arrmean)
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 1.16 GiB for an array with shape (2901, 53540) and data type float64

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
 0.87483196 0.87428023 0.87428023 0.87428023 0.87428023 0.87428023
 0.87428023 0.87428023]
  warnings.warn(

GaussianNB Best Score:  0.874831955922865
GaussianNB Best Params:  {'var_smoothing': 1e-06}

In [14]:
#multinomial nb grid search
mnb_params = {'alpha': [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12, 1e-13]}

mnb_grid = GridSearchCV(mnb, mnb_params, cv=5, n_jobs=-1, verbose=1)

mnb_grid.fit(X_train, y_train)

print('MultinomialNB Best Score: ', mnb_grid.best_score_)
print('MultinomialNB Best Params: ', mnb_grid.best_params_)

Fitting 5 folds for each of 14 candidates, totalling 70 fits
MultinomialNB Best Score:  0.9360387574807637
MultinomialNB Best Params:  {'alpha': 1}

In [15]:
#bernoulli nb grid search
bnb_params = {'alpha': [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12, 1e-13]}

bnb_grid = GridSearchCV(bnb, bnb_params, cv=5, n_jobs=-1, verbose=1)

bnb_grid.fit(X_train, y_train)

print('BernoulliNB Best Score: ', bnb_grid.best_score_)
print('BernoulliNB Best Params: ', bnb_grid.best_params_)

Fitting 5 folds for each of 14 candidates, totalling 70 fits
BernoulliNB Best Score:  0.9608522846015009
BernoulliNB Best Params:  {'alpha': 1}

### Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier

#parameter grid for random forest
rfc_param_grid = {
    'n_estimators': range(100, 600, 100),
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : range(10, 60, 10),
    'criterion' :['gini', 'entropy']
}

rfc_grid = GridSearchCV(RandomForestClassifier(random_state = 101), rfc_param_grid, cv = 5, n_jobs = -1)

rfc_grid.fit(X_train, y_train)

print('Random Forest Best Score: ', rfc_grid.best_score_)
print('Random Forest Best Params: ', rfc_grid.best_params_)

c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
250 fits failed out of a total of 750.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
113 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
137 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan 0.96719141
 0.96774352 0.96829524 0.96802014 0.96912245 0.94431044 0.95092543
 0.95395839 0.95478522 0.95533656        nan        nan        nan
        nan        nan 0.96581362 0.96691631 0.96746727 0.9685711
 0.9677439  0.94844457 0.95175074 0.9550607  0.95423349 0.95561319
        nan        nan        nan        nan        nan 0.96719217
 0.96801976 0.96774428 0.96829524 0.96829524 0.94679168 0.95589019
 0.95809518 0.95754574 0.95699402        nan        nan        nan
        nan        nan 0.96553776 0.96691669 0.96719293 0.9677439
 0.96774428 0.95092619 0.95616377 0.95809632 0.9597515  0.96030284
        nan        nan        nan        nan        nan 0.96829486
 0.96719255 0.96691745 0.96802014 0.9677439  0.95037295 0.9553377
 0.95837029 0.95974998 0.96030094        nan        nan        nan
        nan        nan 0.96636459 0.96691631 0.96857148 0.96884734
 0.97022552 0.94403306 0.95368253 0.95561167 0.95478408 0.95698984
        nan        nan        nan        nan        nan 0.96829524
 0.9677439  0.96801976 0.96801976 0.96801976 0.94871891 0.95423311
 0.95506146 0.95671625 0.95754308        nan        nan        nan
        nan        nan 0.9685711  0.96884696 0.9685711  0.96884658
 0.96829524 0.95009936 0.95588791 0.95726722 0.95754384 0.95947449
        nan        nan        nan        nan        nan 0.96691707
 0.96774428 0.96746803 0.9677439  0.96746803 0.94816719 0.9575408
 0.95809556 0.95837105 0.95864767        nan        nan        nan
        nan        nan 0.96746727 0.96829562 0.96857072 0.96884658
 0.96829486 0.95037485 0.95533732 0.95726798 0.95644153 0.9578197 ]
  warnings.warn(

Random Forest Best Score:  0.9702255153415027
Random Forest Best Params:  {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 500}

In [4]:
#save best models
import joblib

In [ ]:

#train using best parameters
bnb_best = BernoulliNB(alpha = 1)
bnb_best.fit(X_train, y_train)

joblib.dump(bnb_best, 'models/bnb_best.joblib')

rfc_best = RandomForestClassifier(criterion = 'entropy', max_depth = 10, max_features = 'sqrt', n_estimators = 500, random_state = 101)
rfc_best.fit(X_train, y_train)

joblib.dump(rfc_best, 'models/rfc_best.joblib')

### SVM

In [6]:
#if for whatever reason you need to run the notebook at least skip this cell
from sklearn.svm import SVC

#parameter grid for support vector machine
svc_grid = {
    'C': [1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'poly', 'sigmoid'],
    'degree': [2, 3]
}

svc_grid = GridSearchCV(SVC(random_state = 101), svc_grid, cv = 5, n_jobs = -1)

svc_grid.fit(X_train, y_train)

print('SVC Best Score: ', svc_grid.best_score_)
print('SVC Best Params: ', svc_grid.best_params_)

c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
1 fits failed out of a total of 480.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\svm\_base.py", line 190, in fit
    X, y = self._validate_data(
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\utils\validation.py", line 1301, in check_X_y
    X = check_array(
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\utils\validation.py", line 1012, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\utils\_array_api.py", line 745, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\pandas\core\generic.py", line 2153, in __array__
    arr = np.asarray(values, dtype=dtype)
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 1.16 GiB for an array with shape (2902, 53540) and data type float64

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [0.50206859 0.91260758 0.5569355  0.5544516  0.91260758        nan
 0.76178778 0.91260682 0.77943954 0.97187765 0.8332011  0.96912131
 0.50206859 0.81362325 0.5569355  0.5544516  0.81362325 0.68210696
 0.76178778 0.80866002 0.77943954 0.97187765 0.82299497 0.96912131
 0.50206859 0.91260758 0.55528071 0.56796048 0.91260758 0.67962686
 0.78687717 0.91288306 0.77116595 0.96691669 0.8991006  0.94954878
 0.50206859 0.81362325 0.55528071 0.56796048 0.81362325 0.67962686
 0.78687717 0.8094876  0.77116595 0.96691669 0.76592533 0.94954878
 0.50206859 0.91260758 0.55500484 0.56796048 0.91260758 0.67907552
 0.78687717 0.91260758 0.76951154 0.96774352 0.91260682 0.91288382
 0.50206859 0.81362325 0.55500484 0.56796048 0.81362325 0.67907552
 0.78687717 0.81362325 0.76951154 0.96774352 0.79404997 0.91288382
 0.50206859 0.91260758 0.55500484 0.56796048 0.91260758 0.67879966
 0.78687717 0.91260758 0.76951154 0.96774352 0.91288306 0.89138216
 0.50206859 0.81362325 0.55500484 0.56796048 0.81362325 0.67879966
 0.78687717 0.81362325 0.76951154 0.96774352 0.80866002 0.89138216]
  warnings.warn(

SVC Best Score:  0.9718776479528831
SVC Best Params:  {'C': 1, 'degree': 2, 'gamma': 0.001, 'kernel': 'rbf'}

In [ ]:
#train best model and save it
svc_best = SVC(C = 1, degree = 2, gamma = 0.001, kernel = 'rbf', random_state = 101, probability = True)

svc_best.fit(X_train, y_train)

joblib.dump(svc_best, 'models/svc_best.joblib')

['models/svc_best.joblib']

### Deep Neural Network

In [16]:
#tensorflow model for fake news binary classification
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

model = Sequential()

model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(X_train.shape[1],), kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

c:\Users\voldy\Desktop\college stuff\CS350\venv\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
history = model.fit(X_train, y_train, epochs = 20, batch_size = 64, validation_data = (X_test, y_test))

Epoch 1/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 8s 116ms/step - accuracy: 0.8296 - loss: 8.3755 - val_accuracy: 0.7190 - val_loss: 5.4859
Epoch 2/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step - accuracy: 0.9712 - loss: 4.5843 - val_accuracy: 0.8161 - val_loss: 3.4500
Epoch 3/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step - accuracy: 0.9822 - loss: 2.8257 - val_accuracy: 0.9254 - val_loss: 2.3638
Epoch 4/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 94ms/step - accuracy: 0.9769 - loss: 2.0236 - val_accuracy: 0.9704 - val_loss: 1.5848
Epoch 5/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step - accuracy: 0.9793 - loss: 1.3989 - val_accuracy: 0.9685 - val_loss: 1.2615
Epoch 6/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step - accuracy: 0.9744 - loss: 1.1548 - val_accuracy: 0.9608 - val_loss: 1.0597
Epoch 7/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step - accuracy: 0.9768 - loss: 0.9467 - val_accuracy: 0.9717 - val_loss: 0.9198
Epoch 8/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step - accuracy: 0.9797 - loss: 0.8838 - val_accuracy: 0.9678 - val_loss: 0.8894
Epoch 9/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 96ms/step - accuracy: 0.9775 - loss: 0.8027 - val_accuracy: 0.9543 - val_loss: 0.7982
Epoch 10/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 94ms/step - accuracy: 0.9744 - loss: 0.7453 - val_accuracy: 0.9627 - val_loss: 0.8402
Epoch 11/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 99ms/step - accuracy: 0.9641 - loss: 1.0177 - val_accuracy: 0.9691 - val_loss: 0.8589
Epoch 12/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 98ms/step - accuracy: 0.9787 - loss: 0.7561 - val_accuracy: 0.9627 - val_loss: 0.7354
Epoch 13/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 98ms/step - accuracy: 0.9749 - loss: 0.6946 - val_accuracy: 0.9627 - val_loss: 0.6051
Epoch 14/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - accuracy: 0.9767 - loss: 0.5762 - val_accuracy: 0.9608 - val_loss: 0.7844
Epoch 15/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - accuracy: 0.9677 - loss: 0.7844 - val_accuracy: 0.9608 - val_loss: 0.7021
Epoch 16/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - accuracy: 0.9761 - loss: 0.6145 - val_accuracy: 0.9653 - val_loss: 0.6793
Epoch 17/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - accuracy: 0.9820 - loss: 0.6493 - val_accuracy: 0.9576 - val_loss: 0.7850
Epoch 18/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - accuracy: 0.9718 - loss: 0.7457 - val_accuracy: 0.9672 - val_loss: 0.8919
Epoch 19/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - accuracy: 0.9763 - loss: 0.7948 - val_accuracy: 0.9646 - val_loss: 0.8547
Epoch 20/20
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 98ms/step - accuracy: 0.9812 - loss: 0.7471 - val_accuracy: 0.9543 - val_loss: 0.7552

In [18]:
#save keras model file for later
model.save('models/dnn_tf.keras')